name: LBmenu
version: '1.0'
main: me.wethink.lBmenu.LBmenu
api-version: '1.21'
authors: [ WeThink ]
folia-supported: true
softdepend: [ PlaceholderAPI, Topper, ajLeaderboards ]

libraries:
  - com.github.ben-manes.caffeine:caffeine:3.2.3

commands:
  lbmenu:
    description: Open a leaderboard GUI or reload config
    usage: /lbmenu <placeholder|reload>
    aliases: [ lb ]

permissions:
  lbmenu.reload:
    description: Allows reloading the LBmenu config
    default: op
